### ISSUE TITLE
How to use in combination with gulp-sass

### ISSUE THREAD

**Issue by lmartins** [sindresorhus/gulp-autoprefixer#8] opened 2014-09-29 07:30 UTC
Hi,

Im trying to use gulp-autoprefixer in combination with gulp-sass and gulp-sourcemaps.
My gulpfile task looks like this:
```
gulp.task('sass', function () {
  gulp.src( config.SASS.src )
    .pipe( plugins.sourcemaps.init() )
    .pipe( plugins.sass() )
    .pipe( plugins.autoprefixer (
      "last 1 versions", "> 10%", "ie 9"
      ))
    .pipe( plugins.sourcemaps.write('./') )
    .pipe( gulp.dest( config.SASS.build ) )
    .pipe( browserSync.reload({ stream: true }) );
});
```
The `plugins.` prefix is related to `gulp-load-plugins`

Without gulp-sass the task runs fine, but with it it throws the following error:
```
[08:26:51] Finished 'sass' after 3.32 ms
gulp-sourcemap-write: source file not found:/Users/luismartins/Sites/00_LAB/wp-multisite/wp-content/themes/wip053/src/sass/main.css
```

Should I be running autoprefixer as a separate task after CSS compilation?

Thanks.

**Comment by polarathene** [comment] 2015-01-12 06:46
Inline/external sourcemaps work fine, I've come across blog posts and the like saying the issue is with autoprefixer but have been looking into the issue and discovered libsass isn't outputting proper sourcemaps. If you're using libsass check that the sourcemap it produces is functional, in my experience it links to the scss file but fails to match lines. I found out why and you can see [here](https://github.com/sass/node-sass/issues/619). The good news is it should be fixed with libsass 3.2 :)

@myqianlan There are lot of options, you can write separate files using two destinations or tasks, or change name with `gulp-rename`. You can also include the scss->css source in the sourcemap, that can go inside your css, just use `.pipe(gulp_sourcemaps.write())`, then before using `gulp-autoprefixer` add `.pipe(gulp_sourcemaps.init({loadMaps: true}))`. 

Autoprefixer works, and handles sourcemap properly. Problem is libsass is making invalid sourcemap, all the mappings from the css to scss are at the beginning of the file, autoprefixer is not at fault. Until libsass 3.2 (and node-sass/gulp-sass work with it), you will not get valid sourcemap for your scss files.

**Comment by myqianlan** [comment] 2015-01-12 07:23
@polarathene  thanks,I will take a try.

**Comment by polarathene** [comment] 2015-01-14 13:02
@myqianlan There was an update to `gulp-sass` today, I've talked about it and provided some code sample [here](https://github.com/sindresorhus/gulp-autoprefixer/issues/10#issuecomment-69910254) both inline and external sourcemaps with embedded or external sources.

Hope it helps the rest of you too :)

**Comment by Avcajaraville** [comment] 2015-02-17 17:14
Still love to get a solution for this.

Weird thing is that it is working fine for one of my files (we have an admin & public css); when I compile something, in one of the views (public), everything works fine; but for the other (admin), google developers tools cant even show the file that create the style (the file that you see on the style tab when inspecting, right to the classes name).

This is getting very weird... If I disable then autoprefixer, everything works fine.

Anybody ?

**Comment by 1Copenut** [comment] 2015-03-29 16:28
I was having this same issue today, but got it to work correctly by moving the Autoprefixer .pipe rule below the sourcemaps.write:

gulp.task('sass', function() {
  gulp.src('app/styles/sass/*.scss')
  .pipe(sourcemaps.init())
    .pipe(sass())
    .pipe(sourcemaps.write())
    .pipe(autoprefixer({browsers: ['last 2 versions']}))
    .pipe(gulp.dest('app/styles/css'));
});

**Comment by lmartins** [comment] 2015-03-29 16:47
Im going to try that, but I suspect that will skew your line numbers in the css inspector because autoprefixer will add lines to the code, changing the location your source map originally haves.

**Comment by superbiche** [comment] 2015-03-29 22:11
After 3 hours trying every possible combination, seems that @1Copenut solution works.
I had to tweak it a little bit by adding a filter to prevent autoprefixer reading my sourcemaps. And surprisingly, the line numbers seem right (made a few checks and what Chrome reports matches my .scss sources).  
      
      // config.sass.src = 'theme/assets/src/scss/**/*.{scss,sass}'
      // config.sass.dest = 'theme/assets/css/"
      gulp.task('styles', ['clean:styles'], function () {
   
        // Prevent reading sourcemaps to autoprefix them or make sourcemaps of sourcemaps
        var filter = gulpFilter(['*.css', '!*.map']);

        return gulp.src(config.sass.src)
          .pipe(plumber())
          .pipe(sourcemaps.init())
          .pipe(sass({ errLogToConsole: true }))
          .pipe(sourcemaps.write('./'))
          .pipe(filter)
          .pipe(autoprefixer({ browsers: ['last 2 versions' ], cascade: true }))
          .pipe(filter.restore())
          .pipe(gulp.dest(config.sass.dest));
      });

The gulp-plugins I use:
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^2.1.0",
    "gulp-filter": "^2.0.2",
    "gulp-plumber": "^1.0.0",
    "gulp-sass": "^1.3.3",
    "gulp-sourcemaps": "^1.5.1",

Hope that helps.

**Comment by fricks** [comment] 2015-04-02 19:23
I can't run autoprefixer :/
What could be wrong with my task?

"gulp-autoprefixer": "^2.1.0"
"gulp-ruby-sass": "^0.7.1"

```
gulp.task('sass-app', function () {
  return gulp.src(config.sassPath + '/style.scss')
  .pipe(sass({
    style: 'normal',
    loadPath: [
    './app/sass',
    config.bowerDir + '/bootstrap-sass-official/assets/stylesheets',
    config.bowerDir + '/loaders.css/src/'
    //config.bowerDir + '/fontawesome/scss',
    //config.bowerDir + '/Hover/scss',
    ]
  })
  .on("error", notify.onError(function (error){
    return "Error: " + error.message;
  })))
  //.pipe(autoprefix(['last 2 version']))
  .pipe(autoprefixer({browsers: ['last 2 versions']}))
  .pipe(gulp.dest('./assets/css'))
  .pipe(notify('CSS OK!'));
});
```

**Comment by 1Copenut** [comment] 2015-04-06 02:08
@fricks Can you elaborate on not being able to run autoprefixer? Is it throwing an error to your console, or is the gulp task completing without adding any rules?

**Comment by 1Copenut** [comment] 2015-04-06 02:10
@superbiche Your additions to my quick and dirty solution worked great. I've included gulp-plumber and gulp-filter into my own task, and all seems to be in order. Thank you for the improvement.

**Comment by jedmao** [comment] 2015-04-06 04:40
@superbiche or @fricks, can either of you submit a PR to the [gulp recipes](https://github.com/gulpjs/gulp/tree/master/docs/recipes)? This looks like it could be a great addition.

**Comment by jmagnusson** [comment] 2015-04-12 15:40
I'm not having the same luck with @superbiche's solution...

`$ gulp styles`:
```
[17:34:24] Using gulpfile ~/apps/myapp/gulpfile.js
[17:34:24] Starting 'clean-styles'...
[17:34:24] Finished 'clean-styles' after 13 ms
[17:34:24] Starting 'styles'...
[17:34:25] Plumber found unhandled error:
 Error in plugin 'gulp-autoprefixer'
Message:
    "/sport/styles/fonts.scss" is not in the SourceMap.
Details:
    fileName: /Users/jacob/apps/hestra/web/hestra_web/static/shared/styles/main.css
[17:34:25] Finished 'styles' after 809 ms
```

`$ cat gulptasks/styles.coffee`:
```coffee
autoprefixer = require('gulp-autoprefixer')
sass = require('gulp-sass')
sourcemaps = require('gulp-sourcemaps')
plumber = require('gulp-plumber')
gulpFilter = require('gulp-filter')
config = require('./config')

gulp.task('styles', ['clean-styles'], ->
  # Prevent reading sourcemaps to autoprefix them or make sourcemaps of sourcemaps
  filter = gulpFilter(['*.css', '!*.map'])

  return gulp.src("#{config.STYLE_PATH}/main.scss")
    .pipe(plumber())
    .pipe(sourcemaps.init())
    .pipe(sass({ errLogToConsole: true }))
    .pipe(sourcemaps.write('./'))
    .pipe(filter)
    .pipe(autoprefixer({ browsers: ['last 2 versions' ], cascade: true }))
    .pipe(filter.restore())
    .pipe(gulp.dest(config.STYLE_PATH_DIST))
)
```

`$ npm ls --depth 0`:
```
├── gulp@3.8.11
├── gulp-autoprefixer@2.1.0
├── gulp-filter@2.0.2
├── gulp-plumber@1.0.0
├── gulp-sass@1.3.3
├── gulp-sourcemaps@1.5.1
```

**Comment by dmnplb** [comment] 2015-04-16 19:06
Thank you, @superbiche. Your solution worked.
Here's my gulp task (I've replaced gulp-filter with gulp-if):

```js
gulp.src(…)
    .pipe($.sourcemaps.init())
    .pipe($.sass({
      precision: 10,
      errLogToConsole: true,
      // indentedSyntax: true, → Sass Syntax
      outputStyle: 'nested'
    }))
    .pipe($.sourcemaps.write('.'))
    .pipe($.if(['*.css', '!*.map'], $.autoprefixer()))
    .pipe(gulp.dest(…));
```

Packages:
```shell
├── gulp@3.8.11
├── gulp-autoprefixer@2.1.0
├── gulp-if@1.2.5
├── gulp-sass@1.3.3
├── gulp-sourcemaps@1.5.2
```

**Comment by 1Copenut** [comment] 2015-04-16 19:34
@jmagnusson Is it possible your Gulpfile is not working because you're running a Ruby-style string interpolation on the return line? You might try this:

`return gulp.src(config.STYLE_PATH + '/main.scss')`

and see if that resolves the error.

**Comment by 1Copenut** [comment] 2015-04-16 19:35
@dmnplb I like your solution to use the $.if statement for Autoprefixer.

**Comment by jmagnusson** [comment] 2015-04-17 08:30
@1Copenut I don't believe so. It's just CoffeeScript which is transformed into that very string you wrote.

**Closed** 2015-04-19 14:44 UTC
Labels: question, sourcemaps

**Comment by jmagnusson** [comment] 2015-04-20 09:04
@sindresorhus Why was this closed?

**Comment by sindresorhus** [comment] 2015-04-20 09:11
It's not an issue with this plugin, but rather gulp-sass (or rather libsass). I've gotten reports that it should be resolved in the unreleased gulp-sass 2.0: https://github.com/dlmanning/gulp-sass/tree/2.x

**Comment by jmagnusson** [comment] 2015-04-20 15:14
@sindresorhus Thanks for the info. Do we have any gulp-sass issues touching this?

**Comment by pjlong** [comment] 2015-04-21 22:59
@1Copenut 's solution worked for me in Chrome using:

    "autoprefixer": "^5.1.1",
    "gulp": "^3.8.11",
    "gulp-autoprefixer": "^2.1.0",
    "gulp-sass": "^1.3.3",
    "node-sass": "^2.0.1"

**Comment by justnorris** [comment] 2015-04-30 15:02
This works for me for now, same versions as @pjlong 
~~~
	gulp.src("#{Config.sass.source}/app.sass")
		.pipe maps.init()
		.pipe sass {
					   precision: 3,
					   outputStyle: 'nested'
					   indentedSyntax: true
				   }
		.on("error", error_handle)
		.pipe maps.write('.')
		.pipe(g_if(['*.css', '!*.map'], autoprefixer()))
		.pipe gulp.dest(Config.build)
~~~

**Comment by justnorris** [comment] 2015-05-01 09:12
Turns out the gulp.if solution doesn't work at all. It just skips autoprefixer task. Noticed that only now when tried to CSS animations in Chrome 42 ( which still requires -webkit- ). Now what ?

**Comment by pjlong** [comment] 2015-05-01 15:25
@justnorris.  Looks like @ahdinosaur's solution was working all along. You will have to upgrade to gulp-sass 2.x branch, however: `npm install dlmanning/gulp-sass#2.x` (and make sure to update to the most recent node-sass as well).


Here's the bare-bones implementation:

    gulp.task('sass', function () {
        return gulp.src(paths.css.src_files)
            .pipe(sourcemaps.init())
                .pipe(sass())
            .pipe(sourcemaps.write())
            .pipe(sourcemaps.init({loadMaps: true}))
                .pipe(autoprefixer())
            .pipe(sourcemaps.write())
            .pipe(gulp.dest(paths.css.dist));
    });

Note: this is only for inline maps, I don't think I've successfully got external maps to work.

**Comment by clempat** [comment] 2015-05-01 17:55
From my side while debugging I saw that the sourcemap was overwritten because of the source file name different (for my case, first app.scss and then app.css) 
That happened at this point:
https://github.com/mozilla/source-map/blob/master/lib/source-map/source-map-generator.js#L194 

I still don't know how/where to fix it

**Comment by clempat** [comment] 2015-05-01 18:27
I would arrive to this solution: https://github.com/floridoo/vinyl-sourcemaps-apply/compare/master...clempat:master Is that making sense to you ?

**Comment by justnorris** [comment] 2015-05-06 15:23
~~~
├── autoprefixer@5.1.1
├── browser-sync@2.7.1
├── coffee-script@1.9.2
├── connect@3.3.5
├── gulp@3.8.11
├── gulp-autoprefixer@2.2.0
├── gulp-coffee@2.3.1
├── gulp-concat@2.5.2
├── gulp-download@0.0.1
├── gulp-minify-css@1.1.1
├── gulp-notify@2.2.0
├── gulp-open@0.3.2
├── gulp-run@1.6.8
├── gulp-sass@2.0.0
├── gulp-shell@0.4.1
├── gulp-sourcemaps@1.5.2
├── gulp-uglifyjs@0.6.2
├── gulp-util@3.0.4
├── gulp-watch@4.2.4
├── gulp-wrap@0.11.0
├── merge-stream@0.1.7
└── node-sass@3.0.0
 npm -v
  2.7.4
node -v
  v0.12.2

~~~
Now I can't compile, I get:

~~~
[18:22:25] Starting 'sass'...

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: config
  1:1  invalid top-level expression
~~~


With this config:
~~~
	gulp.src("#{Config.sass.source}/app.sass")
		.pipe maps.init()
		.pipe sass
		   indentedSyntax: true
		   precision: 3,
		   errLogToConsole: true
		.pipe maps.write()
		.pipe maps.init( loadMaps: true )
		.pipe autoprefixer()
		.pipe maps.write()
		.pipe gulp.dest(Config.build)
~~~

**Comment by clempat** [comment] 2015-05-06 15:31
is the comma after `indentedSyntax: true` not needed ?

**Comment by justnorris** [comment] 2015-05-06 16:10
Nope :)
Actually the comma after precision: 3 is not needed too, looks messy, but works totally fine anyway.

**Comment by clempat** [comment] 2015-05-06 16:22
Are u sure it is connected to autoprefixer ? does pipe sass works alone ?

**Comment by justnorris** [comment] 2015-05-06 16:27
gulp-sass isn't just ready for production yet.

I ended up using gulp-ruby-sass with these settings:
~~~

	sass("#{Config.sass.source}/app.sass", {
		precision: 3
		style: 'expanded'
		sourcemap: true
	})
	.pipe autoprefixer()
	.pipe maps.write()
	.pipe gulp.dest(Config.build)

~~~


Works purrfectly.

**Comment by dsebastien** [comment] 2015-06-05 08:42
@dmnplb Thanks, your solution works perfectly for me too: https://github.com/dsebastien/midnightLightV2/blob/master/gulp/tasks/styles.js

**Comment by Jiasm** [comment] 2016-10-09 07:22
You just need to execute autoprefixer before sourcemap.

**Comment by englishextra** [comment] 2016-11-24 13:56
this works for me:

```
/*!
 * npmjs.com/package/gulp-autoprefixer
 * const gulp = require('gulp');
 * const sourcemaps = require('gulp-sourcemaps');
 * const autoprefixer = require('gulp-autoprefixer');
 * const concat = require('gulp-concat');
 * gulp.task('default', () =>
 * gulp.src('src')
 * .pipe(sourcemaps.init())
 * .pipe(autoprefixer())
 * .pipe(concat('all.css'))
 * .pipe(sourcemaps.write('.'))
 * .pipe(gulp.dest('dest')));
 */
var gulp = require('gulp');
var gutil = require('gulp-util');
var bower = require('bower');
var concat = require('gulp-concat');
var sass = require('gulp-sass');
var sourcemaps = require('gulp-sourcemaps');
var autoprefixer = require('gulp-autoprefixer');
var cleancss = require('gulp-clean-css');
var rename = require('gulp-rename');
var sh = require('shelljs');
var paths = {
	sass: ['./diy/libs/spa-englishextra/scss/**/*.scss']
};
gulp.task('default', ['sass']);
gulp.task('sass', function (done) {
	gulp.src('./diy/libs/spa-englishextra/scss/bundle.scss')
	.pipe(sass())
	.pipe(sourcemaps.init())
	.pipe(autoprefixer())
	.on('error', sass.logError)
	/* .pipe(gulp.dest('./diy/libs/spa-englishextra/css/')) */
	.pipe(cleancss({
			keepSpecialComments: 0
		}))
	.pipe(rename({
			extname: '-compiled.min.css'
		}))
	.pipe(sourcemaps.write('.'))
	.pipe(gulp.dest('./diy/libs/spa-englishextra/css/'))
	.on('end', done);
});
gulp.task('watch', function () {
	gulp.watch(paths.sass, ['sass']);
});
gulp.task('install', ['git-check'], function () {
	return bower.commands.install()
	.on('log', function (data) {
		gutil.log('bower', gutil.colors.cyan(data.id), data.message);
	});
});
gulp.task('git-check', function (done) {
	if (!sh.which('git')) {
		console.log(
			'  ' + gutil.colors.red('Git is not installed.'),
			'\n  Git, the version control system, is required to download Ionic.',
			'\n  Download git here:', gutil.colors.cyan('http://git-scm.com/downloads') + '.',
			'\n  Once git is installed, run \'' + gutil.colors.cyan('gulp install') + '\' again.');
		process.exit(1);
	}
	done();
});
```
see here: https://www.npmjs.com/package/gulp-autoprefixer#source-maps
