### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by PawelGIX** [sindresorhus/gulp-autoprefixer#48] opened 2015-11-09 19:07 UTC
My task:
```
gulp.task('css', [], function() {
  return gulp.src(['sass/styles.scss'])
    .pipe(sourcemaps.init())
    .pipe(sass().on('error', sass.logError))
    .pipe(autoprefixer({
           browsers: ['last 2 versions'],
           cascade: false
    }))
    .pipe(sourcemaps.write('./css/'))
    .pipe(gulp.dest('./css/'));
});
```

Result:
```


/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
    at LazyResult.async (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:75:21)
    at DestroyableTransform._transform (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-autoprefixer/index.js:24:6)
    at DestroyableTransform.Transform._read (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
    at writeOrBuffer (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
    at DestroyableTransform.Writable.write (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:246:11)
    at write (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Applications/MAMP/htdocs/oneplusone.pl/layouts/roomore/node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)

```

**Comment by PawelGIX** [comment] 2015-11-09 20:02
Resolved by updating Node

**Comment by sindresorhus** [comment] 2015-11-10 07:46
Duplicate of https://github.com/sindresorhus/gulp-autoprefixer/issues/45.

**Closed by sindresorhus** 2015-11-10 07:46 UTC
