### ISSUE TITLE
ReferenceError: Promise is not defined

### ISSUE THREAD

**Issue by ivoputzer** [sindresorhus/gulp-autoprefixer#49] opened 2015-11-12 16:25 UTC
It seems that `postcss` (one of `gulp-prefixer`'s deps) uses promises while nodejs does not officially implement that api yet; Have you considered using a version of `postcss` that does not break the behaviour?

```
node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152
        this.processing = new Promise(function (resolve, reject) {
                              ^
ReferenceError: Promise is not defined
  at LazyResult.async (node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:152:31)
  at LazyResult.then (node_modules/gulp-autoprefixer/node_modules/postcss/lib/lazy-result.js:75:21)
  at DestroyableTransform._transform (node_modules/gulp-autoprefixer/index.js:24:6)
  at DestroyableTransform.Transform._read (node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:10)
  at DestroyableTransform.Transform._write (node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:160:12)
  at doWrite (node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:333:12)
  at writeOrBuffer (node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:319:5)
  at DestroyableTransform.Writable.write (node_modules/gulp-autoprefixer/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:246:11)
  at write (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:117:20)
  at emitReadable_ (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at DestroyableTransform.endStream [as _flush] (node_modules/gulp-concat/index.js:98:10)
  at DestroyableTransform.<anonymous> (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
  at DestroyableTransform.g (events.js:180:16)
  at DestroyableTransform.emit (events.js:92:17)
  at finishMaybe (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
  at endWritable (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
  at DestroyableTransform.Writable.end (node_modules/gulp-concat/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
  at Stream.onend (stream.js:79:10)
  at Stream.emit (events.js:117:20)
  at DestroyableTransform.<anonymous> (node_modules/event-stream/index.js:50:16)
  at DestroyableTransform.emit (events.js:117:20)
  at endReadableNT (node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:958:12)
  at afterTick (node_modules/gulp-sass/node_modules/through2/node_modules/readable-stream/node_modules/process-nextick-args/index.js:11:8)
  at process._tickCallback (node.js:448:13)
```

**Comment by sindresorhus** [comment] 2015-11-12 17:05
Duplicate of https://github.com/sindresorhus/gulp-autoprefixer/issues/45 and #48.

**Closed by sindresorhus** 2015-11-12 17:05 UTC
